### ISSUE TITLE
Error: Couldn't open ...buildout.cfg

### ISSUE THREAD

**Issue by natea** [plone/plone-devstart#5]
When I select Plone 4.2, I get the following error:
- Obtaining skeleton buildout
  
  > Downloading: buildout-skeleton.zip (27964 bytes)
  >   27964  [100.00%]
  > Done
- Bootstrapping buildout
  
  > Downloading: bootstrap.py (3807 bytes)
  >   3807  [100.00%]
  > Running: /Users/nateaune/code/plonedevstart/bin/python bootstrap.py
  > While:
  > Initializing.
  > Error: Couldn't open /Users/nateaune/code/plonedevstart/buildout.cfg

*\* ERROR: Bootstrap failed. Please see above for details.

**Comment by aclark4life** [comment]
Fixed in #8
